### ISSUE TITLE
Cloudflare verification fails

### ISSUE THREAD

**Issue by eNkKVS4HxHc9jaq** [matthaigh27/ChatGPT-android-app#10] opened 2023-03-02 21:01 UTC
When launched the cloudflare verification banner does not load and is instead white.

![Screenshot_20230302-215645_ChatGPT.png](https://user-images.githubusercontent.com/71072643/222551590-c3087368-1a29-4b45-88a6-bf971192d810.png)

Tapping the empty box at the spot to confirm you're not a robot like usual does not work. This unfortunately breaks the entire app.

**Comment by matthaigh27** [comment] 2023-03-13 12:02
@eNkKVS4HxHc9jaq Hmm, I can see you're using Mullvad VPN, are you sure you wouldn't have something on your device potentially blocking Cloudflare's CDN?

**Comment by erikvb** [comment] 2023-03-13 21:01
@matthaigh27 I have the same issue. Not using any VPN, just using wifi... Normal browser version also works fine.


https://user-images.githubusercontent.com/1823580/224831298-ce560bb0-4dc8-4975-b25b-c70ba94020bc.mp4

**Comment by seelebrn** [comment] 2023-03-13 22:42
I can confirm this too !

**Comment by matthaigh27** [comment] 2023-03-15 11:45
I think cloudflare might have changed something, though I can't reproduce this on my device? Can anyone point me to some threads of similar issues so I can look for solutions. I've seen 2 others on other repos in the past 2 weeks but neither had solutions...

**Comment by matthaigh27** [comment] 2023-03-16 06:22
Should be fixed in the latest, found out it happened in chrome on desktop when using mobile views in the responsive viewer. It seems to like the latest useragent for chrome on android so hope it works for everyone!

**Closed by matthaigh27** 2023-03-16 06:22 UTC
